### ISSUE TITLE
can AbLang2 be applied to nanobody?

### ISSUE THREAD

**Issue by pengzhangzhi** [TobiasHeOl/AbLang2#3]
Hi, Thanks for the great work! Wondering can AbLang2 be applied to nanobody?

**Comment by TobiasHeOl** [comment]
Hello and thank you very much! While it has technically seen some nanobodies when pre-training with unpaired chains (a single study in OAS contains nanobodies), I have not explored this and I would not expect it to be that good for nanobodies.

I hope this answered your question!
